version: "3.7"
services:
  db:
    # image: mysql:8.0
    build: ./mysql/
    container_name: mysql
    
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_SECRET_ROOT_PASSWORD"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

      # Where our data will be persisted
    volumes:
      - ./data:/var/lib/mysql # for data
      - ./scripts:/scripts
      - ./mysql/startscript:/docker-entrypoint-initdb.d
    networks:
      - tomcat_network

  web:
    # image:  tomcat:9.0.37-jdk8
    build: ./tomcat/
    container_name: tomcat

    # ---- IMPORTANT ----
    # In production (on digitalOcean)  replace ALL values below with your own secret values
    # NEVER COMMIT/PUSH this file/project
    environment:
      CONNECTION_STR: "jdbc:mysql://db:3306/startcode"
      USER: "dev" # database user to use in tomcat apps
      PW: "ax2" # database password
      DEPLOYED: "PROD"

    ports:
     - "8081:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
 
    networks:
      - tomcat_network
    
      # copy the tomcat manager app and make it accessible outside of localhost (then start tomcat)
    command: sh -c "cp -r /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/manager && mv /tmp/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml && catalina.sh run"
    
networks:
  tomcat_network:
    driver: bridge
